# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "01_pydecorator.ipynb",
         "wrapper": "01_pydecorator.ipynb",
         "timer": "01_pydecorator.ipynb",
         "waste_time": "01_pydecorator.ipynb",
         "get_params": "01_pydecorator.ipynb",
         "trace": "01_pydecorator.ipynb",
         "greet": "01_pydecorator.ipynb",
         "random_greet": "01_pydecorator.ipynb",
         "greet_many": "01_pydecorator.ipynb",
         "GREETINGS": "01_pydecorator.ipynb",
         "register": "01_pydecorator.ipynb",
         "true_or_false": "01_pydecorator.ipynb",
         "reversed": "01_pydecorator.ipynb",
         "robber_language": "01_pydecorator.ipynb",
         "REGISTERED": "01_pydecorator.ipynb",
         "count_calls": "10_pydecorator_adv.ipynb",
         "fibonacci": "10_pydecorator_adv.ipynb",
         "CountCalls": "10_pydecorator_adv.ipynb"}

modules = ["pydecorator.py",
           "pyscraper.py",
           "pyencoding.py",
           "pydecorator_adv.py"]

doc_url = "https://danhphan.github.io/explore/"

git_url = "https://github.com/danhphan/explore/tree/master/"

def custom_doc_links(name): return None
