# AUTOGENERATED! DO NOT EDIT! File to edit: 03_pyencoding.ipynb (unless otherwise specified).

__all__ = []

# Cell
import functools
import logging
import random
import time
from collections import defaultdict

import sklearn
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
