# AUTOGENERATED! DO NOT EDIT! File to edit: 02_pyscraper.ipynb (unless otherwise specified).

__all__ = []

# Cell
from parsel import Selector
from urllib.request import urlopen
import requests
import pandas as pd
import time